steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/senpilot/agent:${_TAG}', '.']
images: ['${_REGION}-docker.pkg.dev/$PROJECT_ID/senpilot/agent:${_TAG}']
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _REGION: us-east1
  _TAG: latest
timeout: 1200s
